name: Image audit

on:
  pull_request:
    branches:
      - production
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  image-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find Unused Files
        id: find-files
        run: |
          # Find all .png and .svg files, excluding those in the ./static directory
          FILES=$(find . -type f \( -name "*.png" -o -name "*.svg" \) -not -path "./static/*")

          # Check if files are referenced in any markdown file
          UNUSED_FILES=""
          for FILE in $FILES; do
            FILENAME=$(basename "$FILE")
            if ! grep -q -r -F --exclude-dir=.github "$FILENAME" --include="*.md" .; then
              UNUSED_FILES+="$FILE\n"
            fi
          done

          # If there are unused files, output them
          if [ -n "$UNUSED_FILES" ]; then
            echo "::set-output name=unused_files::$UNUSED_FILES"
          fi

      - name: Create Issue if Unused Files Found
        if: steps.find-files.outputs.unused_files
        env:
          UNUSED_FILES: ${{ steps.find-files.outputs.unused_files }}
        run: |
          # Create the issue and reference the unused_files variable
          echo "The following files are not referenced in any markdown file:\n${UNUSED_FILES}" > unused_files.txt
          curl --silent -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/cloudflare/cloudflare-docs/issues" \
            -d "{\"title\": \"Unused Image Files Found\", \"body\": \"$(cat unused_files.txt)\", \"assignees\": [\"kodster28\", \"haleycode\"]}"

      - name: Delete Unused Files
        if: steps.find-files.outputs.unused_files
        run: |
          # Create a new branch with the date-appended name
          BRANCH_NAME="image-cleanup-$(date +%Y%m%d)"
          
          git checkout -b $BRANCH_NAME

          # Delete the unused files
          while IFS= read -r FILE; do
            if [ -f "$FILE" ]; then
              git rm --cached "$FILE"
              rm "$FILE"
            else
              echo "File not found: $FILE"
            fi
          done <<< "${{ steps.find-files.outputs.unused_files }}"

          # Commit the changes
          git commit -m "Remove unused image files"

          # Push the branch
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        if: steps.find-files.outputs.unused_files
        env:
          ISSUE_NUMBER: ${{ steps.create-issue.outputs.issue_number }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Remove unused image files"
          title: "Remove Unused Image Files"
          body: |
            This PR removes the unused image files identified in issue #${{ env.ISSUE_NUMBER }}.
            How to address this issue:
            1. Check each string using the Find/Replace within your local IDE.
            2. Remove the specified files.
            3. Create a PR with "closes #${{ env.ISSUE_NUMBER }}" in the description.
            (If you remove images that are referenced, the Compile step will actually fail because you'll be introducing broken links.)
          branch: "image-cleanup-$(date +%Y%m%d)"
          branch-suffix: timestamp
          labels: "image cleanup"
          base: production

