name: Codeowner Assignment

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - production

jobs:
  assign-users:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: CodeOwnersParser
        id: CodeOwnersParser
        uses: Gamer025/CodeOwnersParser@v1
          
      #Assign users
      - name: Assign users
        if: steps.CodeOwnersParser.outputs.owners != ''
        uses: Gamer025/AssignUser@v1
        with:
          separator: ' '
          users: ${{ steps.CodeOwnersParser.outputs.owners }}